# Server Configuration
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/orebi?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
jwt.secret=AS&*@#$%^&*()_+QWERTY123456
jwt.expiration=86400000

# Logging Configuration
logging.level.org.springframework=INFO
logging.level.com.orebi=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Spring Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin

#api link
api.base.url=https://localhost:8080

#reset password
reset.password.url=http://localhost:8080/reset-password

# Email Configuration (if needed)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tp301103@gmail.com
spring.mail.password=zhfe iawa mpqm tkvt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.sender.name=Orebi Shop
mail.sender.email=tp301103@gmail.com

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

cloudinary.cloud-name=dk97ayceg
cloudinary.api-key=641923739451543
cloudinary.api-secret=6RdF5mRbrDwaGFmGgtrPOCPXIh8

# VNPay Configuration
vnpay.merchant-id=S0DRSW33
vnpay.secret-key=Q7ZFQUA0OH9KSTAKZIBNOGT1C4598ZUL
vnpay.return-url=http://localhost:8080/api/payment/vnpay/callback
vnpay.base-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
SuccessRedirectUrl="link FE nếu thanh toán thành công"


# Banking Information
banking.account-number=123456789
banking.account-name=NGUYEN VAN A
banking.bank-name=VIETCOMBANK

spring.servlet.multipart.enabled=true
