# Server Configuration
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/orebi?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
jwt.secret=AS&*@#$%^&*()_+QWERTY123456
jwt.expiration=86400000

# Logging Configuration
logging.level.org.springframework=INFO
logging.level.com.orebi=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Spring Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin

#api link
api.base.url=https://localhost:8080

#reset password
reset.password.url=http://localhost:3000/reset-password/

# Email Configuration (if needed)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tp301103@gmail.com
spring.mail.password=zhfe iawa mpqm tkvt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.sender.name=Orebi Shop
mail.sender.email=tp301103@gmail.com

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

cloudinary.cloud-name=dk97ayceg
cloudinary.api-key=641923739451543
cloudinary.api-secret=6RdF5mRbrDwaGFmGgtrPOCPXIh8

# VNPay Configuration
vnpay.merchant-id=S0DRSW33
vnpay.secret-key=Q7ZFQUA0OH9KSTAKZIBNOGT1C4598ZUL
vnpay.return-url=http://localhost:8080/api/payment/vnpay/callback
vnpay.base-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
SuccessRedirectUrl=http://localhost:3000/payment-success/


# Banking Information
banking.account-number=123456789
banking.account-name=NGUYEN VAN A
banking.bank-name=VIETCOMBANK

#GO-SHIP
goship.id=185
goship.base-url=https://sandbox.goship.io/api/v2
goship.secretkey=ifTLb4yHvJ2e5y6Q0rS2tU5G3rI7dRAgAZohrI1b
goship.token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImZiNTY0NzhlMGRjMmExNTEzYzZmMjg5ZDA1M2RkZTIzNTlhNTczZjAwNjQxOGNlNjU1MGJmOTA4ZWUwMjY0N2RhMWU5MWNkZjI4OTdmOTMzIn0.eyJhdWQiOiIxMyIsImp0aSI6ImZiNTY0NzhlMGRjMmExNTEzYzZmMjg5ZDA1M2RkZTIzNTlhNTczZjAwNjQxOGNlNjU1MGJmOTA4ZWUwMjY0N2RhMWU5MWNkZjI4OTdmOTMzIiwiaWF0IjoxNzQ5NzUxNzcwLCJuYmYiOjE3NDk3NTE3NzAsImV4cCI6MjA2NTI4NDU3MCwic3ViIjoiMzk4NiIsInNjb3BlcyI6W119.nUpAKS1uAdmRUpk9e_jZJ0AiCCwrbrzPldGlvj9WqHU2pnp1YWOxGDO8nnCvBm_IFmiWrcf004eEwTVFkFKrakuVshntatN4O7kdf_tUtSjOEffmfJMdPg7IFOhBNL29s43bDkAGoIf9FgNIhBV29zpd2O5HcnWmTuKUjI-ER9khoifAGGfJZml1mnyUeshUtWkCr_tew_FFN7HOdjQhTOw84lWpnVWzrupBKGE2pMFNa5CrLAAkmmWRDD0bUlTFSOIVfVbitpFf_XZRHdolP013Mweq7xcM2jqmfqpYScVOZjUfXGl9uyQQ2Ohc4KU3TYNOC9HZ6u7MJR4IssUZh4ndwN69NBaSIbx5pNlF9h5vxFJdIleRLw_O7StDFNuYUBpQSCguNv3eNR8vknMvW6HgnCLc4PP4MrI4wSdFta0H7U6L3svozgGe4Wm4_DihB9CTY7wKVQQ0X9sRhfaIj9czS4AuD7rvJwpITFcOkxvm3PesfZpd2itXluU5G7fAort1zMVwpsmW7dxauYeVY-PlmsN-xznlIOw8WiGL0UqEFmfkmue81mx5igCDpisILzSYUTRBf514tn5i_4_Bwk7tOf7cWzfFNaI6IPcTUOoKtboAGd27XD1AXiUU_WKRacdXWm9zTV1v34e6XGWV28OMv6TvtCdThzwuVo68d8E
#image 
spring.servlet.multipart.enabled=true
